" Maintainer: JG
" Date: June 4 
" License: (c) VRA, GPL-2 or newer
" --------------------------------------------------
" dotfiles/vim/vimrc

" sets up syntax highlighting
syntax enable

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

"=========================================================
"=========================================================

set clipboard=unnamed                                        " yank and paste with the system clipboard
set ignorecase                                               " case-insensitive search
set relativenumber number                                    " sets line numbers
highlight LineNr ctermfg=grey
set tabstop=4                                                " sets tabs to 4 spaces
set softtabstop=2                                            " insert mode tab and backspace use 2 spaces
set expandtab 
set shiftwidth=4 smarttab                                    " normal mode indentation commands use 2 spaces
set laststatus=2                                             " always show statusline
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,eol:¬,nbsp:·,trail:·                   " remove trailing space
set spelllang=en                                             " English spellcheck
set spell
set colorcolumn=80                                           " color columns beyond 80 characters
highlight ColorColumn ctermbg=red guibg=red
set incsearch                                                " search as you type
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set showcmd
set smartcase                                                " case-sensitive search if any caps
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                                 " show a navigable menu for tab completion
set wildmode=longest,list,full

" save on escape
"inoremap <Esc> <Esc>:w<CR>

" sets parenthetical highlighting to just bold
hi MatchParen cterm=bold ctermbg=Black ctermfg=none          

" sets noexpandtab for Makefiles
if &ft == 'make'
    setlocal noexpandtab
    setlocal tabstop=4
endif

"=========================================================
"=========================================================
" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'
Plug 'junegunn/seoul256.vim'
Plug 'dense-analysis/ale'             "providing linting (syntax checking and semantic errors)
Plug 'vim-airline/vim-airline'        "Lean & mean status/tabline for vim that's light as air
Plug 'vim-airline/vim-airline-themes'
Plug 'ncm2/ncm2'                      "slim, fast and hackable completion framework
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-github'
Plug 'ncm2/ncm2-syntax'
Plug 'ncm2/ncm2-jedi'
Plug 'ncm2/ncm2-vim'
Plug 'ervandew/supertab'
Plug 'luochen1990/rainbow'
Plug 'godlygeek/tabular'
Plug 'jalvesaq/Nvim-R'                "Vim's support to edit R code
Plug 'jalvesaq/vimcmdline'            "Send code to command line interpreter

" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

"List ends here. Plugins become visible to Vim after this call.
call plug#end()

