
##
# Your previous /Users/Momo/.bash_profile file was backed up as /Users/Momo/.bash_profile.macports-saved_2015-07-20_at_13:46:46
##

# MacPorts Installer addition on 2015-07-20_at_13:46:46: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

##
# Your previous /Users/Momo/.bash_profile file was backed up as /Users/Momo/.bash_profile.macports-saved_2015-11-05_at_23:40:13
##

# MacPorts Installer addition on 2015-11-05_at_23:40:13: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

export GNUTERM='aqua'

#export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="/usr/local/opt/tcl-tk/bin:$PATH"

# bash completion https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

#test -r "/usr/local/etc/bash_completion.d/git-completion.bash" && . "/usr/local/etc/bash_completion.d/git-completion.bash"

source /usr/local/etc/bash_completion.d/git-completion.bash
#source /usr/local/etc/profile.d/bash-completion.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/Momo/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/Momo/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/Momo/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/Momo/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# export anaconda
export PATH="/Users/Momo/anaconda3/bin/:$PATH"

# set PATH so it includes user's private ~/.local/bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# aliases
alias gs="git status"
alias gc="git commit"
alias ll="ls -ltrF"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
