#!/bin/bash
#:set ft=shell
# Author(s): JG
# Maintainer(s): JG
# ============================
# ~/github/dotfiles/bash/bash_profile

#------------------ aliases -------------------------
# navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .4="cd ../../../../"
alias .5="cd ../../../../../"
alias dl="cd ~/Downloads"
alias gitl="cd ~/gitlab"
alias gith="cd ~/github"

# git
alias gs="git status"
alias gc="git commit -m"

# listing 
alias lh="ls -lh"
# List all files colorized in long format
#alias ll="ls -ltrF ${colorflag}"
# List all files colorized in long format, including dot files
alias la="ls -laF ${colorflag}"
# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"


#alias ll="ls -alhG --color=always"
alias ll="ls -lFG --color=always"
#-------------- external functions--------------------

# Creating task #
# $1 is project path
# $2 is task name
function task(){
    if [! -d $1];
    then
        echo 'project path not valid'
    else
        cd $1
        mkdir $2
        cd $2
        mkdir input src output
        tree -C
    fi
}

#------------------ env vars ----------------------------
export CLICOLORS=1
PS1="\[\e[32m\]\w\n@$USER: \[\e[0;00m\]"
export PS1

# make vim the default editor
export EDITOR='vim';
export CEVGIT="/Users/Momo/gitlab"
export PERSONALGIT="/Users/Momo/github"

# colors
export TERM=xterm-256color

# export anaconda
export PATH+=":/Users/Momo/anaconda3/bin/"
export PATH+=":/usr/local/opt/tcl-tk/bin/"
export GNUTERM='aqua'


# set PATH so it includes user's private ~/.local/bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
#-----------------------

##export PATH+="/usr/local/opt/python/libexec/bin/"
## bash completion https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
#[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
##test -r "/usr/local/etc/bash_completion.d/git-completion.bash" && . "/usr/local/etc/bash_completion.d/git-completion.bash"
#source /usr/local/etc/bash_completion.d/git-completion.bash
##source /usr/local/etc/profile.d/bash-completion.sh

## >>> conda initialize >>>
## !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/Momo/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/Momo/anaconda3/etc/profile.d/conda.sh" ]; then
#        . "/Users/Momo/anaconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/Users/Momo/anaconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup


## <<< conda initialize <<<


# MacPorts Installer addition on 2015-07-20_at_13:46:46: adding an appropriate PATH variable for use with MacPorts.
#export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
##
 Your previous /Users/Momo/.bash_profile file was backed up as /Users/Momo/.bash_profile.macports-saved_2015-11-05_at_23:40:13
##
# MacPorts Installer addition on 2015-11-05_at_23:40:13: adding an appropriate PATH variable for use with MacPorts.
#export PATH+="/opt/local/bin"
#export PATH+="/opt/local/sbin"
# Finished adapting your PATH environment variable for use with MacPorts.
