#!/usr/local/bin/bash
#:set ft=shell
# Author(s): JG
# Maintainer(s): JG
# ============================
# ~/github/dotfiles/bash/bash_profile


#------------------ env vars ----------------------------
export LC_ALL='en_US.UTF-8'
export CLICOLORS=1
PS1="\[\e[32m\]\w\n@$USER: \[\e[0;00m\]"
export PS1
export TMPDIR=/home/tmp

# make vim the default editor
export EDITOR='nvim'
export CEVGIT="/Users/Momo/gitlab"
export PERSONALGIT="/Users/Momo/github"

# colors
export TERM=xterm-256color

# gnu core utils (prepend)
if [ $OSTYPE == 'darwin19.5.0' ]; then
    export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
fi

# export anaconda (append)
export PATH+=":/Users/Momo/anaconda3/bin/"
export PATH+=":/usr/local/opt/tcl-tk/bin/"
export GNUTERM='aqua'

# set PATH so it includes user's private ~/.local/bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# powerline-status
if [ $OSTYPE == 'darwin19.5.0' ]; then
    export PATH=$PATH:$HOME/Library/Python/3.7/bin
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    . /Users/Momo/Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
fi

# HRDAG resource utils
export PATH+=":/Users/Momo/github/hrdag/resource-utils/bin/"

# fzf plugin
[ -f ~/.fzf.bash ] && source ~/.fzf.bash


#------------------ aliases -------------------------
# navigation
# https://github.com/chrishwiggins/mise/blob/master/sh/aliases-public.sh
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .4="cd ../../../../"
alias .5="cd ../../../../../"
alias dl="cd ~/Downloads"
alias gitl="cd ~/gitlab"
alias gith="cd ~/github"
alias reload="source ~/.bashrc"
# git
alias gs="git status"
alias gc="git commit -m"
# makes gA add
alias gA="git add -A && git status"
alias gl="git log --pretty=format:'%C(yellow)%h|%Cred%ci|%Cblue%cN| %Creset%s %Cgreen%d %Creset' | head -n20"
alias gpom="git push origin master"
alias gpgp="git pull; git push"

# listing 
alias l='ls --color -lhF --group-directories-first'
alias lh="ls -lh --color=always"
# List all files colorized in long format
#alias ll="ls -ltrF ${colorflag}"
# List all files colorized in long format, including dot files
alias la="ls -laF --color=always"
# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"
#alias ll="ls -alhG --color=always"
alias ll="ls -lFG --color=always"

# fasd and fzf command
alias j='xdir=$(fasd -dl|fzf --tac) && cd "$xdir"'
# fasd plugin
eval "$(fasd --init auto)"

#texmaker editor
alias texmaker="open -a texmaker"

#inspecting R tools
alias inspect-excel="Rscript ~/github/inspection-tools/inspect-excel.R"

# application
#alias rstudio open /Applications/RStudio.app

# spelling while typing is hard
# alias opne open
# alias alais alias
# alias aalias alias
# alias mdkdir mkdir
# alias mkddir mkdir
# alias kdir mkdir
# alias oepn open
# alias fidn find
# alias gttp http
# alias moer more
# alias mroe more

#-------------- external functions--------------------
# makes 'cs' cd and ll
function cs () {
    cd "$1" && ll
    }

# Creating task #
# $1 is task name
function task(){
    mkdir "$1" && cd "$1"
    mkdir input src output
    cd ..
    tree -C
}

#-----------------------

##export PATH+="/usr/local/opt/python/libexec/bin/"
## bash completion https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
#[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
##test -r "/usr/local/etc/bash_completion.d/git-completion.bash" && . "/usr/local/etc/bash_completion.d/git-completion.bash"
#source /usr/local/etc/bash_completion.d/git-completion.bash
##source /usr/local/etc/profile.d/bash-completion.sh

## !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/Momo/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/Momo/anaconda3/etc/profile.d/conda.sh" ]; then
#        . "/Users/Momo/anaconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/Users/Momo/anaconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup



